## Import the Packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('german.data-numeric', delim_whitespace=True, header=None)

In [3]:
df[24] = df[24].apply(lambda x: x - 1)

In [4]:
df.head()

0   1   2   3   4   5   6   7   8   9  ...  15  16  17  18  19  20  21  22  \
0   1   6   4  12   5   5   3   4   1  67 ...   0   0   1   0   0   1   0   0   
1   2  48   2  60   1   3   2   2   1  22 ...   0   0   1   0   0   1   0   0   
2   4  12   4  21   1   4   3   3   1  49 ...   0   0   1   0   0   1   0   1   
3   1  42   2  79   1   4   3   4   2  45 ...   0   0   0   0   0   0   0   0   
4   1  24   3  49   1   3   3   4   4  53 ...   1   0   1   0   0   0   0   0   

   23  24  
0   1   0  
1   1   1  
2   0   0  
3   1   0  
4   1   1  

[5 rows x 25 columns]

## Scaling the data
I tried using scaled data, which made no difference. If you are able to increase the accuracy, then PULL REQUEST

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
sc = StandardScaler()

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.iloc[:, :-1]

In [9]:
X

0   1   2    3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20  \
0     1   6   4   12   5   5   3   4   1  67 ...   1   0   0   1   0   0   1   
1     2  48   2   60   1   3   2   2   1  22 ...   1   0   0   1   0   0   1   
2     4  12   4   21   1   4   3   3   1  49 ...   1   0   0   1   0   0   1   
3     1  42   2   79   1   4   3   4   2  45 ...   1   0   0   0   0   0   0   
4     1  24   3   49   1   3   3   4   4  53 ...   1   1   0   1   0   0   0   
5     4  36   2   91   5   3   3   4   4  35 ...   1   0   0   1   0   0   0   
6     4  24   2   28   3   5   3   4   2  53 ...   1   0   0   1   0   0   1   
7     2  36   2   69   1   3   3   2   3  35 ...   1   0   1   1   0   1   0   
8     4  12   2   31   4   4   1   4   1  61 ...   1   0   0   1   0   0   1   
9     2  30   4   52   1   1   4   2   3  28 ...   1   1   0   1   0   0   1   
10    2  12   2   13   1   2   2   1   3  25 ...   1   1   0   1   0   1   0   
11    1  48   2   43   1   2   2   4   2  24 ...   1   0   0   1   0   1   0   
12    2  12   2   16   1   3   2   1   3  22 ...   1   0   0   1   0   0   1   
13    1  24   4   12   1   5   3   4   3  60 ...   1   1   0   1   0   0   1   
14    1  15   2   14   1   3   2   4   3  28 ...   1   1   0   1   0   1   0   
15    1  24   2   13   2   3   2   2   3  32 ...   1   0   0   1   0   0   1   
16    4  24   4   24   5   5   3   4   2  53 ...   1   0   0   1   0   0   1   
17    1  30   0   81   5   2   3   3   3  25 ...   1   0   0   1   0   0   1   
18    2  24   2  126   1   5   2   2   4  44 ...   1   0   1   1   0   0   0   
19    4  24   2   34   3   5   3   2   3  31 ...   1   0   0   1   0   0   1   
20    4   9   4   21   1   3   3   4   3  48 ...   1   1   0   1   0   0   1   
21    1   6   2   26   3   3   3   3   1  44 ...   1   0   0   1   0   1   0   
22    1  10   4   22   1   2   3   3   1  48 ...   2   1   0   1   0   1   0   
23    2  12   4   18   2   2   3   4   2  44 ...   1   0   1   1   0   0   1   
24    4  10   4   21   5   3   4   1   3  26 ...   2   0   0   1   0   0   1   
25    1   6   2   14   1   3   3   2   1  36 ...   1   0   0   1   0   0   1   
26    4   6   0    4   1   5   4   4   3  39 ...   1   0   0   1   0   0   1   
27    3  12   1    4   4   3   2   3   1  42 ...   1   0   0   1   0   1   0   
28    2   7   2   24   1   3   3   2   1  34 ...   1   0   0   0   0   0   1   
29    1  60   3   68   1   5   3   4   4  63 ...   1   0   0   1   0   0   1   
..   ..  ..  ..  ...  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..  ..   
970   2  15   2   15   2   3   3   2   1  22 ...   1   0   0   0   0   0   1   
971   4  24   2   74   1   3   3   4   2  43 ...   1   1   0   1   0   0   1   
972   1  24   1   12   1   1   2   4   4  29 ...   1   1   0   0   1   1   0   
973   1  60   2   73   1   5   3   4   4  36 ...   1   0   0   0   1   1   0   
974   4  30   4   28   1   3   2   2   3  33 ...   1   0   0   1   0   0   1   
975   3  24   2   13   3   3   2   3   3  57 ...   1   0   0   1   0   0   1   
976   2   6   2    8   1   3   2   3   1  64 ...   1   0   0   0   0   0   1   
977   2  18   3   24   5   5   3   2   2  42 ...   1   0   0   1   0   0   1   
978   4  24   3   25   1   5   3   4   3  47 ...   1   1   0   1   0   0   1   
979   2  15   1   13   2   3   4   2   2  25 ...   1   1   0   1   0   1   0   
980   2  30   4   84   1   4   3   2   2  49 ...   1   0   0   1   0   0   1   
981   4  48   2   48   1   1   3   2   3  33 ...   1   0   0   1   0   1   0   
982   3  21   2   29   2   3   2   1   3  28 ...   1   1   0   1   0   0   1   
983   1  36   2   82   1   3   3   2   2  26 ...   1   0   1   1   0   0   1   
984   4  24   4   20   1   4   3   2   2  30 ...   1   0   0   1   0   0   1   
985   1  15   4   14   1   3   2   3   2  25 ...   1   0   0   1   0   1   0   
986   3  42   0   63   1   2   1   1   2  33 ...   1   0   0   1   0   0   1   
987   4  13   2   14   2   1   2   4   1  64 ...   1   0   0   1   0   0   1   
988  

In [10]:
y = df.iloc[:, -1]

In [11]:
y

0      0
1      1
2      0
3      0
4      1
5      0
6      0
7      0
8      0
9      1
10     1
11     1
12     0
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     1
      ..
970    0
971    0
972    1
973    1
974    0
975    0
976    0
977    0
978    1
979    1
980    1
981    1
982    0
983    1
984    0
985    0
986    0
987    0
988    0
989    0
990    0
991    0
992    0
993    0
994    0
995    0
996    0
997    0
998    1
999    0
Name: 24, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
X_train.shape

(700, 24)

In [14]:
sc_X = sc.fit_transform(X_train)

In [15]:
sc_test = sc.transform(X_test)

In [16]:
sc_test.shape

(300, 24)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rfc = RandomForestClassifier(n_estimators = 10000)

In [20]:
rfc.fit(sc_X, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [21]:
rfc_pred = rfc.predict(sc_test)

In [22]:
rfc_pred.shape

(300,)

In [23]:
rfc_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1], d

In [23]:
y_test

521    1
737    0
740    0
660    0
411    0
678    0
626    0
513    0
859    0
136    0
811    0
76     1
636    0
973    1
938    1
899    1
280    0
883    0
761    1
319    0
549    0
174    1
371    0
527    0
210    0
235    1
101    0
986    0
902    0
947    0
      ..
490    0
118    1
900    1
250    0
523    0
9      1
196    0
603    1
81     0
783    1
587    0
797    0
239    0
290    0
211    0
717    0
359    1
449    1
227    1
950    0
946    1
796    1
501    0
464    0
362    0
468    0
935    1
428    0
7      0
155    1
Name: 24, dtype: int64

In [24]:
from sklearn.metrics import (classification_report, confusion_matrix)

In [25]:
print(classification_report(y_test, rfc_pred))

             precision    recall  f1-score   support

          0       0.78      0.93      0.85       209
          1       0.71      0.40      0.51        91

avg / total       0.76      0.77      0.74       300



In [26]:
print(confusion_matrix(y_test, rfc_pred))

[[194  15]
 [ 55  36]]


In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
lr = LogisticRegression(verbose = 3)

In [30]:
lr.fit(sc_X, y_train)

[LibLinear]

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=3, warm_start=False)

In [31]:
lr_pred = lr.predict(sc_test)

In [32]:
print(classification_report(y_test, lr_pred))

             precision    recall  f1-score   support

          0       0.79      0.90      0.84       209
          1       0.67      0.46      0.55        91

avg / total       0.75      0.77      0.75       300



In [33]:
print(confusion_matrix(y_test, lr_pred))

[[188  21]
 [ 49  42]]


In [34]:
from sklearn.svm import SVC

In [35]:
svc = SVC()

In [36]:
svc.fit(sc_X, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
svc_pred = svc.predict(sc_test)

In [38]:
print(classification_report(y_test, svc_pred))

             precision    recall  f1-score   support

          0       0.76      0.91      0.83       209
          1       0.62      0.34      0.44        91

avg / total       0.72      0.74      0.71       300



In [46]:
from sklearn.model_selection import GridSearchCV

In [51]:
param_grid = {'C':[0.1, 1, 10, 100], 'gamma':[1, 0.1, 0.01, 0.001, 0.0001], 'kernel':['rbf', 'poly']}

In [52]:
grid = GridSearchCV(SVC(), param_grid, verbose=3)

In [54]:
grid.fit(X_train, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits
[CV] kernel=rbf, C=0.1, gamma=1 ......................................
[CV]  kernel=rbf, C=0.1, gamma=1, score=0.7008547008547008, total=   0.8s
[CV] kernel=rbf, C=0.1, gamma=1 ......................................
[CV]  kernel=rbf, C=0.1, gamma=1, score=0.7008547008547008, total=   0.0s
[CV] kernel=rbf, C=0.1, gamma=1 ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.1s remaining:    0.0s


[CV]  kernel=rbf, C=0.1, gamma=1, score=0.7025862068965517, total=   0.1s
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV]  kernel=poly, C=0.1, gamma=1, score=0.6282051282051282, total= 1.6min
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV]  kernel=poly, C=0.1, gamma=1, score=0.6794871794871795, total= 1.9min
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV]  kernel=poly, C=0.1, gamma=1, score=0.6508620689655172, total= 3.0min
[CV] kernel=rbf, C=0.1, gamma=0.1 ....................................
[CV]  kernel=rbf, C=0.1, gamma=0.1, score=0.7008547008547008, total=   0.0s
[CV] kernel=rbf, C=0.1, gamma=0.1 ....................................
[CV]  kernel=rbf, C=0.1, gamma=0.1, score=0.7008547008547008, total=   0.0s
[CV] kernel=rbf, C=0.1, gamma=0.1 ....................................
[CV]  kernel=rbf, C=0.1, gamma=0.1, score=0.7025862068965517, total=   0.0s
[CV] kernel=poly, C=0.1, gamma=0.1 ............

[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed: 60.8min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ['rbf', 'poly'], 'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

 kernel=rbf, C=100, gamma=0.001,

In [48]:
svcGS1 = SVC(kernel='rbf', C=100, gamma=0.001)

In [54]:
# grid.best_params_ 
# to check the best params

In [49]:
svcGS1.fit(sc_X, y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
svcGS1_pred = svcGS1.predict(sc_test)

In [59]:
print(classification_report(y_test, svcGS1_pred))

             precision    recall  f1-score   support

          0       0.79      0.91      0.84       209
          1       0.67      0.43      0.52        91

avg / total       0.75      0.76      0.75       300



# I will be adding better methods when I figure them out.
## Also feel free to Pull Request when you get better accuracy.
